// Checks mira's hand-rolled RoBERTa byte-level BPE (analyze/RobertaTokenizer.cpp) against
// HuggingFace's own tokenizer, token id for token id.
//
// This exists because the failure mode is silent. The CLAP text tower takes token ids, not
// text; feed it ids that are subtly wrong -- one merge applied in the wrong order, a
// leading space attached to the wrong piece -- and it still returns a confident 512-dim
// vector, just one pointing somewhere meaningless. Search results would get quietly worse
// with nothing anywhere reporting an error. Same reasoning as spike/05_dclap_parity on the
// audio side.
//
// The fixture (models/similarity-embeddings/dclap/roberta-parity.tsv) is generated by
// lab/export_roberta_tokenizer.py and holds real queries plus the cases a byte-level BPE
// most often gets wrong: leading/trailing whitespace, mixed case, hyphens, apostrophes,
// digits, non-ASCII, emoji, and the empty string.
#include "../src/mira/analyze/RobertaTokenizer.h"

#include <fstream>
#include <iostream>
#include <sstream>

int main(int argc, char** argv) {
    if (argc < 4) {
        std::cerr << "usage: tokenizer_parity <vocab.tsv> <merges.txt> <parity.tsv>\n";
        return 2;
    }
    mira::RobertaTokenizer tokenizer(argv[1], argv[2]);
    if (!tokenizer.ok()) {
        std::cerr << "tokenizer failed to load: " << tokenizer.error() << "\n";
        return 2;
    }

    std::ifstream fixture(argv[3]);
    if (!fixture) {
        std::cerr << "can't open fixture " << argv[3] << "\n";
        return 2;
    }

    std::string line;
    int pass = 0, fail = 0;
    while (std::getline(fixture, line)) {
        auto tab = line.rfind('\t');
        if (tab == std::string::npos) continue;
        auto text = line.substr(0, tab);
        auto expected = line.substr(tab + 1);

        std::ostringstream got;
        auto ids = tokenizer.encode(text);
        for (size_t i = 0; i < ids.size(); ++i) {
            if (i > 0) got << ",";
            got << ids[i];
        }
        if (got.str() == expected) {
            ++pass;
        } else {
            ++fail;
            std::cout << "  MISMATCH [" << text << "]\n    want " << expected
                      << "\n    got  " << got.str() << "\n";
        }
    }
    std::cout << "  " << pass << " tokenizer parity cases pass, " << fail << " fail\n";
    return fail == 0 ? 0 : 1;
}
